package view;

import java.awt.Component;
import java.awt.Container;
import java.awt.LayoutManager;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;

/**
 * Separates GUI elements with it's position and style.
 * 
 * @author Zbigniew Malcherczyk (zbigmal353@student.polsl.pl)
 * @version 1.0
 */
public class LayoutGenerator
{
    /**
     * Creates translation tab style and layout that was generated by designer.
     * 
     * @param root the main program container
     * @param userInputArea GUI element where user puts data
     * @param userInputAreaLabel GUI element that describes input area.
     * @param userInputAreaScroll GUI element that makes input area scrollable.
     * @param userOutputArea GUI element where user sees result.
     * @param userOutputAreaLabel GUI element that describes result area.
     * @param userOutputAreaScroll GUI element that makes input area scrollable
     * @param translatorSelectLabel GUI element that describes selector.
     * @param translatorSelect GUI element to select translator.
     * @param translateActionSubmitButton GUI element which triggers translation.
     *
     * @return generated LayoutManager
     */
    public LayoutManager createTranslatorTab(
        Container root,
        JTextArea userInputArea,
        JLabel userInputAreaLabel,
        JScrollPane userInputAreaScroll,
        JTextArea userOutputArea,
        JLabel userOutputAreaLabel,
        JScrollPane userOutputAreaScroll,
        JLabel translatorSelectLabel,
        TranslatorSelect translatorSelect,
        JButton translateActionSubmitButton
    ) {
        GroupLayout layout = new GroupLayout(root);
        
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout
                                .createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(userOutputAreaScroll, GroupLayout.Alignment.TRAILING)
                                .addComponent(userInputAreaLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userInputAreaScroll)
                                .addGroup(
                                    GroupLayout.Alignment.TRAILING,
                                    layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            layout
                                                .createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                .addComponent(translatorSelectLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(translatorSelect, 0, 170, Short.MAX_VALUE)
                                        )
                                        .addGap(18, 18, 18)
                                        .addComponent(translateActionSubmitButton, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                                )
                                .addComponent(userOutputAreaLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        )
                        .addContainerGap()
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING,
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userInputAreaLabel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userInputAreaScroll, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(translatorSelectLabel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(
                            layout
                                .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(translatorSelect, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(translateActionSubmitButton)
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(userOutputAreaLabel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userOutputAreaScroll, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()
                )
        );
        
        return layout;
    }
    
    /**
     * Creates dictionary table with style and layout that was generated by designer.
     * 
     * @param root main program container.
     * @param child to add to main panel.
     * 
     * @return generated LayoutManager.
     */
    public LayoutManager createTableTab(Container root, Component child)
    {
        GroupLayout layout = new GroupLayout(root);
        
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING,
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(child, GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addContainerGap()
                )
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING,
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(child, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addContainerGap()
                )
        );
        
        return layout;
    }
}
